name: Node Setup

on: [push]

jobs:
  eslint:
    name: Run eslint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repo
        uses: actions/checkout@v2

      - name: Setup Node
        run: npm --prefix './project/' ci

      - name: Run Lint Check
        run: npm --prefix './project/' run lint
