name: JSDocs Generation and Push to Docs repo

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [staging, pipeline-testing, main]

jobs:
  jsdocs:
    name: JSDocs push to docs repo
    runs-on: ubuntu-latest

    steps:
      - name: Push to another repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "./project/jsdocs"
          destination-github-username: "docs"
          destination-repository-name: "MarinatedCuyitosDocs"
          user-email: docs@cuyitos.net
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
