name: Lint and Testing

on:
  push:
    branches-ignore: [main]
  # Since this is already ran for every push, will already have run for the most recent pull request.
  # pull_request:
  #   branches: [staging, pipeline-testing, main]

jobs:
  integration-testing:
    name: Run ESLint and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repo
        uses: actions/checkout@v2

      - name: Setup Node
        run: npm --prefix './project/' ci

      - name: Run Lint Check
        run: npm --prefix './project/' run lint

      - name: Run Tests
        run: npm --prefix './project/' run test
