name: Lint
on: [push]
jobs:
  run-linter:
    name: Run linters
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Git repo
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v1
        
      - name: Run our local setup command
        run: npm install
        
      - name: Run ESLint
        run: npx run eslint . --ext .js,.jsx,.ts,.tsx
      
