name: Lint

# on: [push]

on:
  push:
    branches-ignore: [jsdoc]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [staging]

jobs:
  run-linter:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1

      - name: Setup Linter (semistandard in our case so that we can use semicolons.)
        run: npm install semistandard -g

      - name: Install Snazzy for cleaner output from semistandard
        run: npm install snazzy -g

      # Piping our semistandard output to snazzy to clean it up more for readability.
      - name: Run Linter again printing out result
        run: semistandard --verbose | snazzy
